version: "3.9"
services:
  nginx:
    container_name: socket_nginx
    hostname: socket_nginx
    build:
      dockerfile: Dockerfile
    image: socket-nginx-img
    restart: always
    ports:
      - "5173:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
  app:
    container_name: socket_app
    hostname: socket_app
    build:
      dockerfile: DockerfilePython
    image: socket-app-img
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"





