"""empty message

Revision ID: b8295910fd78
Revises: 13fb2d897240
Create Date: 2022-11-11 00:04:52.176296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8295910fd78'
down_revision = '13fb2d897240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_bind_info', sa.Column('min_distance', sa.Integer(), nullable=True))
    op.add_column('phone_bind_info', sa.Column('max_distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_bind_info', 'max_distance')
    op.drop_column('phone_bind_info', 'min_distance')
    # ### end Alembic commands ###
