"""empty message

Revision ID: e40b9b27b4dd
Revises: 
Create Date: 2022-09-15 21:17:10.248775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40b9b27b4dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_bind_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.Column('match_car_type', sa.String(length=500), nullable=True),
    sa.Column('screen_car_type', sa.String(length=500), nullable=True),
    sa.Column('target_address', sa.String(length=500), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_bind_info')
    # ### end Alembic commands ###
